services:
  - type: web
    name: entitlemate-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn entitlemate_backend_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000